
services:
  app:
    image: node:20-alpine
    command: >
      sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm dev"
    volumes:
      - /.:/c-zo
    working_dir: /c-zo
    tty: true
    ports:
      - "4000:4000"
    environment:
      HOST: 0.0.0.0
    networks:
      - c-zo
  postgres:
    image: postgres:17
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_password_manager
    ports:
      - "5432:5432"
    networks:
      - c-zo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $${POSTGRES_DB}"]
      timeout: 1s
      interval: 5s
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - c-zo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      timeout: 5s
      interval: 10s
      retries: 3

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  c-zo:
    driver: bridge